### ISSUE TITLE
Error when create override for UTC6

### ISSUE THREAD

**Issue by Darkomen78** [autopkg/jessepeterson-recipes#66]
I got this error. What can I do ?
autopkg make-override UniversalTypeClient6.munki
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2453, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2447, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1782, in make_override
    recipe, search_dirs=search_dirs)
  File "/usr/local/bin/autopkg", line 1389, in get_trust_info
    'path': os_path_compressuser(processor_path),
  File "/usr/local/bin/autopkg", line 1349, in os_path_compressuser
    elif pathname.startswith(home_dir):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by jessepeterson** [comment]
Never seen that before. Looks more like an issue with autopkg itself. Can you create other overrides?

**Comment by Darkomen78** [comment]
Other overrides are create with no errors. I also try after a reboot.

**Comment by jpiel** [comment]
Just tried here  and i have the same issue :
`MacBook-J-Piel:~ jayce$ autopkg make-override UniversalTypeClient6.munki
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2453, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2447, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1782, in make_override
    recipe, search_dirs=search_dirs)
  File "/usr/local/bin/autopkg", line 1389, in get_trust_info
    'path': os_path_compressuser(processor_path),
  File "/usr/local/bin/autopkg", line 1349, in os_path_compressuser
    elif pathname.startswith(home_dir):
AttributeError: 'NoneType' object has no attribute 'startswith'
`

**Comment by gregneagle** [comment]
You've triggered a bug in the 1.0.4 release, though I suspect that you might get different Traceback with the previous release.

In any case, the underlying issue is that it can't find the com.github.scriptingosx.SharedProcessors/FileTemplate processor, presumably since you haven't yet added the com.github.scriptingosx repo, and this recipe relies on a shared processor from that repo.

**Comment by Darkomen78** [comment]
The fix works fine. Thanks !

**Comment by jessepeterson** [comment]
Thanks @gregneagle :)
